In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:\\DOCS\\data_analyst\\project\\E-Commerce Sales Analysis\\Dataset\\ecommerce_sales_analytics_5000.csv")
df.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [3]:
df.describe(include= 'all')

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
count,5000.000000,5000,5000.000000,5000,5000,5000.000000,5000.000000,5000.000000,5000,5000.000000,5000.000000,5000.000000
unique,NaN,5000,NaN,4,4,NaN,NaN,NaN,3,NaN,NaN,NaN
top,NaN,1/1/2022,NaN,Electronics,West,NaN,NaN,NaN,Card,NaN,NaN,NaN
freq,NaN,1,NaN,1777,1289,NaN,NaN,NaN,2270,NaN,NaN,NaN
mean,12500.500000,NaN,1505.701200,NaN,NaN,4.044800,308.418774,0.179984,NaN,6.118800,2.973980,1021.955148
std,1443.520003,NaN,290.836902,NaN,NaN,2.020398,169.259369,0.101404,NaN,3.153264,1.157722,825.584219
min,10001.000000,NaN,1000.000000,NaN,NaN,1.000000,15.150000,0.000000,NaN,1.000000,1.000000,11.210000
25%,11250.750000,NaN,1253.000000,NaN,NaN,2.000000,161.895000,0.090000,NaN,3.000000,2.000000,354.527500
50%,12500.500000,NaN,1510.000000,NaN,NaN,4.000000,309.890000,0.180000,NaN,6.000000,3.000000,796.650000
75%,13750.250000,NaN,1761.000000,NaN,NaN,6.000000,455.557500,0.270000,NaN,9.000000,4.000000,1515.690000
max,15000.000000,NaN,1999.000000,NaN,NaN,7.000000,599.960000,0.350000,NaN,11.000000,5.000000,4119.330000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   object
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), object(4)
memory usage: 468.9+ KB

In [13]:
print("Null values:\n", df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

Null values:
 order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
total_price         0
discounted_price    0
dtype: int64

Duplicate rows: 0

In [6]:
df['customer_id'].nunique()

989

In [7]:
df[['customer_id', 'order_id']] = df[['customer_id', 'order_id']].astype(str)

In [8]:
df['total_price'] = df['quantity'] * df['unit_price']
df['discounted_price'] = df['total_price'] - (df['discount'] * df['total_price'])
df['discounted_price'] = df['discounted_price'].round(2)
df['order_date'] = pd.to_datetime(df['order_date'])

df[['total_price', 'discounted_price', 'revenue', 'order_date']].head()

   total_price  discounted_price  revenue order_date
0      2615.55           1883.20  1883.20 2022-01-01
1       334.18            304.10   304.10 2022-01-02
2       933.84            644.35   644.35 2022-01-03
3      2622.35           2569.90  2569.90 2022-01-04
4       699.35            468.56   468.56 2022-01-05

In [15]:
(np.isclose(df['discounted_price'], df['revenue'], atol=0.01)).all()

np.True_

In [10]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue', 'total_price', 'discounted_price'],
      dtype='object')

In [11]:
%pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\sagar\appdata\local\programs\python\python313\lib\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in c:\users\sagar\appdata\local\programs\python\python313\lib\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\users\sagar\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sagar\appdata\local\programs\python\python313\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
from sqlalchemy import create_engine

username = 'root'
password = 'sagar2006'
host = 'localhost'
port = '3306'
database = 'ecommerce_sales_database'

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

table_name = 'ecommerce_sales_data'
df.to_sql(table_name, con=engine, if_exists='replace', index=False)

result = pd.read_sql(
    f'SELECT * FROM {table_name} LIMIT 5',
    con=engine
)

result

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue,total_price,discounted_price
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20,2615.55,1883.20
1,10002,2022-01-02,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10,334.18,304.10
2,10003,2022-01-03,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35,933.84,644.35
3,10004,2022-01-04,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90,2622.35,2569.90
4,10005,2022-01-05,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56,699.35,468.56